sudo: false
language: node_js
git:
  depth: false
node_js:
  - "8.3"
notifications:
  disabled: true
cache:
  directories:
    - "node_modules"
env:
  NODE_ENV: production
script:
  - yarn test
  - yarn build
deploy:
  skip_cleanup: true
  provider: script
  script: now --local-config=./now.json --token=$NOW_TOKEN -e NODE_ENV=production -e APP_ID=$APP_ID -e WEBHOOK_SECRET=$WEBHOOK_SECRET -e PRIVATE_KEY=$PRIVATE_KEY
  on:
    branch: master